trigger:
  branches:
    include:
    - main
    - master
  paths:
    exclude:
    - NuGet
pr:
  branches:
    include:
    - master
    - main
  paths:
    exclude:
    - NuGet


pool:
  vmImage: 'windows-latest'

variables:
  - group: IronDrawingVersions
  - name: buildConfiguration
    value: 'Debug'
  - name: AssemblyVersion
    value: $(IronDrawingMajorVersion).$(IronDrawingMinorVersion).$(IronDrawingRevisionVersion).$(Build.BuildID)

##### STEPS #####
stages:
## Restore & Build IronDrawing and Publish Artifact
- stage: BuildDrawingLibraries
  displayName: Build IronSoftware.Drawing Libraries
  dependsOn: []
  jobs:
    - template: job_templates/build_drawing_libraries.yml
      parameters:
        publishAssemblies: false
        buildConfiguration: $(buildConfiguration)
## Execute Unit Tests
- template: stage_templates/run_tests_on_pool.yml
  parameters:
    OSPlatform: 'Windows'
    pool:
      vmImage: 'windows-latest'
